security:
    encoders:
        App\Entity\UserApi:
            algorithm: bcrypt
            cost: 12
    providers:
        user_api_provider:
            entity:
                class: App\Entity\UserApi
                property: user
    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: user_api_provider
            json_login:
                check_path:      /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/
            stateless: true
            anonymous: true
            provider: user_api_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            anonymous: true
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
