snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'

    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'metadata:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'result:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'query:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'second_level:'
